### ISSUE TITLE
ESRI Products in tool page

### ISSUE THREAD

**Issue by rl627** [Drexel-UHC/data-tools#14]
@sjmelly I will update the tools page to reflect ESRI's various outputs/products. Can you fill out the following template (you can drag and drop in the comments to upload) so I can upload this info to the website gallery page

Tempalte: [ESRI outputs catolog template.xlsx](https://github.com/Drexel-UHC/data-tools/files/6924303/ESRI.outputs.catolog.template.xlsx)

**Comment by sjmelly** [comment]
I copied Project Descriptions from ArcGIS online Contents. I interpret "Date released" to mean date made public. I added Date Created (copied from ArcGIS online contents). I am assuming we will initially release projects internally and after review make them public. I suppose we may want to have some projects be internal only. For the non-public projects the URLs will work for members of the ArcGIS online groups that include the content. Ran Li is included in those groups. 
[ESRI.outputs.catalog.template_sm.xlsx](https://github.com/Drexel-UHC/data-tools/files/6925224/ESRI.outputs.catalog.template_sm.xlsx)

**Comment by rl627** [comment]
@sjmelly thank you for send this. 

Let me know how this new format works for you! should I add the non-public ones to the gallery or wait untill release?

**Comment by sjmelly** [comment]
I like the new format. I'm thinking we will mostly be using this internally so it could include the non-public tools, but we can talk about this with the group in September

**Comment by rl627** [comment]
Sorry for the late reply!

Sounds good I will leave them off for now. Thanks!!
