### ISSUE TITLE
Replace Bikeability StoryMap with Philadelphia Neighborhood StoryMap

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/data-tools#27]
Information about Philadelphia Neighborhoods StoryMap was entered in Qualtrics survey.
There are more publicly available data sources on bicycle infrastructure available now than when the Bikeability StoryMap was created, so that StoryMap may be out of date. 

---

## Action Items
 
- [x] Remove likability item
- [x] add phil nbh story map

**Comment by sjmelly** [comment]
Let's remove the Bikeability StoryMap

**Comment by ran-codes** [comment]
done!

**Comment by sjmelly** [comment]
@ran-codes There are two apps with titles "Philadelphia Neighborhoods for Public Health Research" The SALURBAL Cities (L1AD & L2) app has an incorrect title. Also the Latin America Urban Areas app shouldn't have the word "Life" in the title.
But it's great to see all of these things compiled together in one place

**Comment by ran-codes** [comment]
## Action Itmes

- [x] Remove `Life` from  Latin_America_Urban_Areas_1_29_20 item
- [x] corrected  `SALURBAL Cities Web Application` title

**Comment by ran-codes** [comment]
thanks for the feedback steve!

should be fixed. feel free to close this issue again if they look okay to you.
